package com.example.demo.service;

import java.util.ArrayList;
import java.util.List;

/**
 * シフト自動生成の実行結果を表すクラス。
 */
public class ShiftGenerationResult {

    private int shortageCount;
    private int overCount;
    private int autoGeneratedCount;
    private int autoTemporaryCount;

    private List<String> warnings = new ArrayList<>();

    public int getShortageCount() { return shortageCount; }
    public void setShortageCount(int shortageCount) { this.shortageCount = shortageCount; }

    public int getOverCount() { return overCount; }
    public void setOverCount(int overCount) { this.overCount = overCount; }

    public int getAutoGeneratedCount() { return autoGeneratedCount; }
    public void setAutoGeneratedCount(int autoGeneratedCount) { this.autoGeneratedCount = autoGeneratedCount; }

    public int getAutoTemporaryCount() { return autoTemporaryCount; }
    public void setAutoTemporaryCount(int autoTemporaryCount) { this.autoTemporaryCount = autoTemporaryCount; }

    public List<String> getWarnings() { return warnings; }
    public void setWarnings(List<String> warnings) { this.warnings = warnings; }

    public void addWarning(String warning) {
        this.warnings.add(warning);
    }
}